# Generated by Django 5.0.7 on 2024-08-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
